accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password', views.change_password, name='change_password'),
]

articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/',views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:pk>/list/',views.article_list, name='article_list'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
]

retry/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.contrib.auth import get_user_model

class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, username, password, **extra_fields)

class User(AbstractUser):
    email = models.EmailField(unique=True)  # 이메일 필드 추가
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    contact_number = models.CharField(max_length=15, blank=True, null=True)

    objects = CustomUserManager()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms
from django.forms import TextInput, EmailInput, NumberInput  # 추가

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('email', 'username', 'password')
        widgets = {
            'email': EmailInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Email'
            }),
        }

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields = ('username', 'password')

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()

accounts/views.py
# import 
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_http_methods
# Import inside project
from .forms import CustomUserCreationForm, CustomUserChangeForm

def login(request):
    if request.method == 'POST':
        # 로그인 처리를 해준다.
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {'form' : form}
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {'form':form}
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['POST'])
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('articles:index')

def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form' : form}
    return render(request, 'accounts/update.html', context)

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form' : form}
    return render(request, 'accounts/change_password.html', context)

templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
    <h1>비밀번호변경</h1>
    <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="변경하기">
    </form>
    <a href="{% url 'articles:index' %}">[목록보기]</a>
{% endblock content %}

templates/accounts/login.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
        <script src="https://tistory3.daumcdn.net/tistory/941717/skin/images/jquery.min.js" type="text/javascript" href="./test.js"></script> 
        <script src="https://tistory3.daumcdn.net/tistory/941717/skin/images/snowfall.jquery.js" type="text/javascript" href="./test.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    </head>
    <body class="body">
        <div class="display-container">
            <div class="all">
                <div class="title">
                    <h1><span>M</span><span>A</span><span>N</span><span>,</span><span>D</span><span>O</span><span>!</span></h1>
                </div>
                <div class="main_img">
                    <img class="mando1" src="{% static 'accounts/source/img/mando1.png' %}" />
                    <img class="mando2" src="{% static 'accounts/source/img/mand02.png' %}" />
                    <img class="mando3" src="{% static 'accounts/source/img/mando3.png' %}" />
                </div>
                <div class="login-wrapper">
                    <form class="loginform" action="{% url 'accounts:login' %}" method="POST" id="login-form">
                            {% comment %} 
                            <input type="text" name="userId" placeholder="이메일">
                            <input type="password" name="userPassword" placeholder="비밀번호"> 
                            {% endcomment %}
                            
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="로그인">
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

templates/accounts/signup.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
        <script src="https://tistory3.daumcdn.net/tistory/941717/skin/images/jquery.min.js" type="text/javascript" href="./test.js"></script> 
        <script src="https://tistory3.daumcdn.net/tistory/941717/skin/images/snowfall.jquery.js" type="text/javascript" href="./test.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    </head>
    <body class="body">
        <div class="display-container">
            <div class="all">
                <div class="title">
                    <h1><span>M</span><span>A</span><span>N</span><span>,</span><span>D</span><span>O</span><span>!</span></h1>
                </div>
                <div class="main_img">
                    <img class="mando1" src="{% static 'accounts/source/img/mando1.png' %}" />
                    <img class="mando2" src="{% static 'accounts/source/img/mand02.png' %}" />
                    <img class="mando3" src="{% static 'accounts/source/img/mando3.png' %}" />
                </div>
                <div class="login-wrapper">
                    <form action="{% url 'accounts:signup' %}" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="회원가입">
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="수정하기">
    </form>
    <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}