articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/',views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:pk>/list/',views.article_list, name='article_list'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
]

retry/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from accounts.models import User

class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    image = models.ImageField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.id}번째글 - {self.title}'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comment')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.content

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ('article',)

articles/views.py
from django.shortcuts import render, redirect
from articles.models import Article, Comment
from .forms import ArticleForm, CommentForm


def index(request):
    if request.user.is_anonymous:
        return redirect('accounts:login')
    articles = Article.objects.filter(author=request.user.id)
    return render(request, 'articles/index.html', {'articles': articles})


def detail(request, pk):
    if request.method == 'POST':
        article = Article.objects.get(pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.save()
        return redirect('articles:detail', article.pk)
    
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    commnets = Comment.objects.filter(article=pk)
    context = {
        'article' : article,
        'article_link' : f'http://127.0.0.1:8000/articles/{request.user.id}/list',
        'comment_form' : comment_form,
        'comments' : commnets,
    }
    return render(request, 'articles/detail.html', context)
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    
    context = {'form' : form}
    return render(request, 'articles/create.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)

    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES,instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', pk=article.pk)
        return redirect('articles:detail', pk=article.pk)
    else:
        form = ArticleForm(instance=article)
    
    context = {'form' : form, 'article':article}
    return render(request, 'articles/update.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)
    
# def comments_create(request, pk):
#     article = Article.objects.get(pk=pk)
#     comment_form = CommentForm(request.POST)
#     if comment_form.is_valid():
#         comment = comment_form.save(commit=False)
#         comment.article = article
#         comment.save()
#     return redirect('articles:detail', article.pk)

def article_list(request, pk):
    articles = Article.objects.filter(author=pk)
    return render(request, 'articles/index.html', {'articles': articles})

templates/articles/create.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'articles/css/create.css' %}">
    <link rel="stylesheet" type=" text/css" href="style.css">
    <title>man-do!</title>
</head>
<h1>CREATE</h1>
<hr>
<form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    
    <input type="submit" value="Submit">
    <div class="display-container">
        <div class="background-image"><img src="{% static 'articles/source/img/page.png' %}" alt="배경"></div>
        
            {% csrf_token %}
            {{ form.as_p }}
            <div class="img-preview"><img src="{% static 'articles/source/img/upload.png' %}" id="uploadTrigger"alt="이미지"></div>
        </div>
    </div>
</form>
<hr>
<a href="{% url 'articles:index' %}">[BACK]</a>

templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="write.css">
        <link rel="stylesheet" type=" text/css" href="style.css">
        <title>man-do!</title>
    </head>
    {% if article.image %}
        <img src="{{ article.image.url }}" >
    {% endif %}
    
    {% if article %}
        <p>글 번호 : {{article.id}}</p>
        <p>글 제목 : {{article.title}}</p>
        <p>글 내용 : {{article.content}}</p>
        <p>생성시각 : {{article.created_at}}</p>
        <p>수정시각 : {{article.updated_at}}</p>
        <hr>
        <a href="{% url 'articles:index' %}">목록보기</a>
        <a href="{% url 'articles:update' article.pk %}">UPDATE</a>
        <form action="{% url 'articles:delete' article.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="DELETE">
        </form>
        <a href="{%url 'articles:index'%}">[back]</a>
    {% else %}
        <p>No article available.</p>
    {%endif%}

    <h5>Comment</h5>
    <hr>
    <h4>댓글 목록</h4>
    <ul>
        {% for comment in comments %}
            <li>{{ comment.content }}</li>
        {% endfor %}
    </ul>
    
    <form action="{ % url 'articles:comments_creaete' article.pk % }" method="POST">
        {% csrf_token %}
        {{ comment_form }}
        <input type="submit" value="작성">
    </form>
{% endblock content%}

templates/articles/index.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8" /> 
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'articles/css/mando.css' %}" />
        <link rel="stylesheet" href="{% static 'articles/css/style.css' %}" />
        <script src="{% static 'articles/js/mando.js' %}"></script>
        <title>man-do!</title>
    </head>
    <body>
      <div>
        <div class="display-container">
          <div class="background-image"><img src="{% static 'articles/source/img/page.png' %}" alt="배경" /></div>
          <div class="user-mold">
            <span id="user-name">{{ user.username }}</span><span>님의 만두판</span>
          </div>
          <div class="image-grid">
            
              {% for articles in articles%}
                {%if articles %}
                <a href="{ % url 'articles:detail' articles.pk% }"><img
                  id="mold1"
                  src="{% static 'articles/source/img/mold.png' %}"
                  alt="만두틀"
                />
              </a>
                {%endif%}
              {%endfor%}
            
          </div>
        <div id="link">
          <img src="link.png" alt="공유하기" onclick="showLinkAlert();copyLink()" />
        </div>
        <img
          id="link-alert"
          src="{% static 'articles/source/img/link-alert.png' %}"
          alt="링크가복사되었습니다"
          style="display: none"
        />
        
        <img id="reset-guide" src="{% static 'articles/source/img/reset_quide.png' %}"alt="만두리셋" style="display: none"  />
        <a href="{% url 'articles:create' %}" class="write-link">글쓰기</a>
      </div>
      
    </body>

templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
<h1>UPDATE</h1>
<form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
<hr>
<a href="{% url 'articles:detail' article.pk %}">[back]</a>
{% endblock content %}